apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secure-file-system-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: securefile.local # Map local or custom DNS hostname
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # Route traffic to the service we defined earlier
            name: secure-file-system-service
            port:
              number: 80
