apiVersion: v1
kind: Secret
metadata:
  name: secure-file-system-secrets
type: Opaque
# stringData allows you to enter secrets in plain text. Kubernetes converts them to base64 automatically.
stringData:
  FLASK_SECRET_KEY: "my-secure-flask-secret-key"
  ADMIN_PASSWORD: "my-new-secure-admin-password"
  ENCRYPTION_KEY: "my-32-character-encryption-key-"
  
  # AWS Configuration details (fill in values to enable S3 storage)
  AWS_ACCESS_KEY_ID: "place_aws_access_key_here"
  AWS_SECRET_ACCESS_KEY: "place_aws_secret_access_key_here"
  AWS_STORAGE_BUCKET_NAME: "place_aws_bucket_name_here"
